version: '3'
services:


  db:
    container_name: starter_db
    image: postgres:latest
    ports:
      - "5489:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=starter_db
